# Generated by Django 3.2.7 on 2021-10-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211004_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters_master',
            name='candidate_pic',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
