# Generated by Django 3.2.7 on 2021-11-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_voters_master_candidate_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_booth_master',
            name='addr4',
            field=models.IntegerField(),
        ),
    ]
