# Generated by Django 3.2.7 on 2021-11-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_election_booth_master_addr4'),
    ]

    operations = [
        migrations.AddField(
            model_name='election_candidate_master',
            name='place_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
